### ISSUE TITLE
Questions about sign and verify

### ISSUE THREAD

**Issue by 99Kies** [StricaHQ/examples-dapp-connector#3]
I want to evoke the wallet to `sign` a `Message("hello, world")`, how should I do it?

**Comment by mehulcs** [comment]
Please use `signData` method from [CIP-30](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0030/README.md). Typhon Wallet injects CIP-30 API `typhoncip30` as well in `window.cardano` object.

**Comment by 99Kies** [comment]
There is no such method, can you provide an example?

```javascript
      const addressResponse = await window.cardano.typhon.getAddress();
      const bech32Address = addressResponse.data;
      console.log('-------------------------');
      console.log(addressResponse)

      let message = 'hello';
      let hexMessage = '';
      for (var i = 0, l = message.length; i < l; i++) {
        hexMessage += message.charCodeAt(i).toString(16);
      }
      console.log("hexMessage: ")
      console.log(hexMessage)
      const dataSignature = await window.cardano.typhoncip30.signData(addressResponse, hexMessage);
      console.log('signature: ')
      console.log(dataSignature)

```

![image](https://github.com/StricaHQ/examples-dapp-connector/assets/45918704/9758a30a-8176-4553-833c-3c78c130a15b)

**Comment by mehulcs** [comment]
Please go through the CIP-30 document at [https://github.com/cardano-foundation/CIPs/blob/master/CIP-0030/README.md](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0030/README.md)

First, you need to call the `enable` method, in return, you get an API object, that API object has multiple methods and `signData` method is one of them.

**Comment by 99Kies** [comment]
cool! 👍
```javascript
      const api = await window.cardano.typhoncip30.enable();

      const hexAddresses = await api.getRewardAddresses();

      const hexAddress = hexAddresses[0];

      console.log(hexAddress)

      let message = 'hello';
      let hexMessage = '';
      for (var i = 0, l = message.length; i < l; i++) {
        hexMessage += message.charCodeAt(i).toString(16);
      }
      console.log("hexMessage: ")
      console.log(hexMessage)
      const dataSignature = await api.signData(hexAddress, hexMessage);
      console.log('signature: ')
      console.log(dataSignature)
```

**Comment by 99Kies** [comment]
@mehulcs  Why is the `RewardAddress` I calculated different from the take address shown in the `Yoroi` wallet?

**my code:**

```javascript
      const hexAddresses = await api.getRewardAddresses();
      const hexAddress = hexAddresses[0];
      console.log(hexAddress)

      let haddress = typhonjs.utils.getAddressFromHex(hexAddress);
      console.log(haddress)
```

**output:**

`stake1uxhjzp0xu008uzsw7ad7yud5w99228txgppfc3yeavqwlgqmmx000`

<img width="570" alt="image" src="https://github.com/StricaHQ/examples-dapp-connector/assets/45918704/b8f2f697-6c64-4094-b37f-03699111d8c2">


**yoroi data:**

`stake1u8y9hzvcpamhe8pumls6c863vt2fslhqvwwavlzs0f0anng95fcwh`

<img width="1153" alt="image" src="https://github.com/StricaHQ/examples-dapp-connector/assets/45918704/a719e5df-15a2-4bbd-abd4-b8eb1263b294">
